version: "2"

services:
  zookeeper:
    #image: wurstmeister/zookeeper
    #image: bitnami/zookeeper
    image: wurstmeister/zookeeper:3.4.6
    container_name: global-zookeeper
    ports:
      - "2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
  kafka:
    #image: wurstmeister/kafka
    #image: bitnami/kafka
    image: wurstmeister/kafka
    container_name: global-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CONNECT_BOOTSTRAP_SERVERS: localhost:9092
      KAFKA_CONNECT_REST_PORT: 8082
      KAFKA_CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      KAFKA_CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      KAFKA_CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: 0
      KAFKA_CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: 0
      KAFKA_CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      KAFKA_CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      KAFKA_CONNECT_INTERNAL_KEY_CONVERTER_SCHEMAS_ENABLE: 0
      KAFKA_CONNECT_INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE: 0
      KAFKA_CONNECT_OFFSET_STORAGE_FILE_FILENAME: "/tmp/connect.offsets"
      KAFKA_CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
  kafka_manager:
    image: obsidiandynamics/kafdrop
    container_name: global-kafka-manager
    depends_on:
      - kafka
    ports:
      - "8181:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092