#pod亲和性
apiVersion: v1
kind: Pod
metadata:
  name: node01
  labels:
    app: node01
spec:
  containers:
    - name: node01
      image: nginx:v1
---

apiVersion: v1
kind: Pod
metadata:
  name: node02
  labels:
    app: node02
spec:
  containers:
    - name: node02
      image: nginx:v1
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - node01  ## 如果pod有标签为app=node01的话，就和他运行在一个
          topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-03
  labels:
    - app: pod-03
spec:
  containers:
    - name: pod-03
      image: nginx:v1
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - node01
          topologyKey: kubernetes.io/hostname

