# 软策略
apiVersion: v1
kind: Pod
metadata:
  name: affinity
  labels:
    app: node-affinity-pod
spec:
  containers:
    - name: with-node-affinity
      image: nginx:v1
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1 ## 权重
          preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: In   ## 期望被调度到node02上
                values:
                  - k8s-node02
