apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
  - apiGroup: [ "" ] # "" indicates the core api group
    resources: [ "pods" ]
    verbs: ["get", "watch", "list"]